""" Constants for pytw module """

""" Constants for REST API calls """
HTTPS_PREFIX = "https://"
API_BASE_URL = "api/"
API_VERSION_1 = "v1/"
API_VERSION_2 = "v2/"
VULNS_URL = "vulns/"
IMPACTS_URL = "impacts/"
URL_FORWARD_SLASH = "/"

""" Some common fields """
ID = "id"
RATING = "rating"

""" Fields of Vuln Object """
VULN_ID = "id"
VULN_TITLE = "title"
VULN_SUMMARY = "summary"
VULN_VULNERABILITY_TYPES = "vulnerability_types"
VULN_CVSS_VECTOR = "cvss_vector"
VULN_CVSS_SCORE = "cvss_score"
VULN_PUBLISHER = "publisher"
VULN_PUBLISHED_DATETIME = "published"
VULN_LAST_MODIFIED_DATETIME = "last_modified"
VULN_NOTIONAL_LAST_MODIFIED_DATETIME = "notional_last_modified"
VULN_LAST_CHANGE = "last_change"
VULN_PRODUCTS = "products"
VULN_PRODUCT_NAME = "name"
VULN_PRODUCT_VENDOR = "vendor"
VULN_PRODUCT_VERSION = "version"
VULN_EXPLOITS = "exploits"
VULN_EXPLOIT_SOURCE = "source"
VULN_EXPLOIT_URL = "url"
VULN_REMEDIATIONS = "remediations"
VULN_REMEDIATION_SOURCE = "source"
VULN_REMEDIATION_URL = "url"
VULN_REMEDIATION_DESCRIPTION = "description"
VULN_REFERENCES = "references"
VULN_ADVISORIES = "advisories"
VULN_RELATED_VULNS = "related_vulns"
VULN_PATCHES = "patches"
VULN_PATCH_ID = "id"
VULN_PATCH_PRODUCT = "product"
VULN_PATCH_URL = "url"
VULN_PATCH_DESCRIPTION = "description"

""" Fields of VulnImpact object """
IMPACT_VULN_ID = "vuln_id"
IMPACT_ASSET_ID = "asset_id"
IMPACT_PRODUCT = "product"
IMPACT_KEYWORD = "keyword"
IMPACT_CONFIDENCE = "confidence"
IMPACT_STATUS = "status"
IMPACT_TIMESTAMP = "timestamp"
IMPACT_VULNERABILITY = "vulnerability"

""" Search Parameters related constants """
SEARCH_PARAM_WINDOW_START = "window_start"
SEARCH_PARAM_WINDOW_END = "window_end"
SEARCH_PARAM_OFFSET = "offset"
SEARCH_PARAM_LIMIT = "limit"

""" Search Filters related constants """
SEARCH_FILTER_RATING = "rating"
SEARCH_FILTER_PUBLISHER = "publisher"
SEARCH_FILTER_FREE_TEXT_SEARCH = "search"
SEARCH_FILTER_RECENT_DISCOVERED_VULNS = "recent-discovered"
SEARCH_FILTER_IMPACTING_VULNS = "impacting"
SEARCH_FILTER_THREATFILTER = "threatfilter"
SEARCH_FILTER_RECENT_IMPACTS = "recent"
SEARCH_FILTER_EXPLOITABLE = "exploitable"
SEARCH_FILTER_PATCH_AVAILABLE = "patch-available"
SEARCH_FILTER_REMEDIATION_AVAILABLE = "remediation-available"
SEARCH_FILTER_TRACKED_VULNS = "tracked"
SEARCH_FILTER_ASSET_IDS = "asset_ids"
SEARCH_FILTER_VULN_IDS = "vuln_ids"
SEARCH_FILTER_THRESHOLD = "threshold"
SEARCH_FILTER_IMPACT_STATUS = "status"

SUPPORTED_SEARCH_FILTERS = [
    SEARCH_FILTER_RATING,
    SEARCH_FILTER_PUBLISHER,
    SEARCH_FILTER_FREE_TEXT_SEARCH,
    SEARCH_FILTER_RECENT_DISCOVERED_VULNS,
    SEARCH_FILTER_IMPACTING_VULNS,
    SEARCH_FILTER_THREATFILTER,
    SEARCH_FILTER_RECENT_IMPACTS,
    SEARCH_FILTER_EXPLOITABLE,
    SEARCH_FILTER_PATCH_AVAILABLE,
    SEARCH_FILTER_REMEDIATION_AVAILABLE,
    SEARCH_FILTER_TRACKED_VULNS,
    SEARCH_FILTER_ASSET_IDS,
    SEARCH_FILTER_VULN_IDS,
    SEARCH_FILTER_THRESHOLD,
    SEARCH_FILTER_IMPACT_STATUS
]
SEARCH_FILTERS = "filters"
