""" Constants for pytw module """

""" Constants for REST API calls """
HTTPS_PREFIX = "https://"
API_BASE_URL = "api/"
API_VERSION_1 = "v1/"
RECENT_VULNS_URL = "threats/recent/"
URL_FORWARD_SLASH = "/"

""" Fields of Threat Object """
VULN_ID = "id"
VULN_TITLE = "title"
VULN_SUMMARY = "summary"
VULN_VULNERABILITY_TYPES = "vulnerability_types"
VULN_CVSS_VECTOR = "cvss_vector"
VULN_CVSS_SCORE = "cvss_score"
VULN_RATING = "rating"
VULN_PUBLISHED_DATETIME = "published"
VULN_LAST_MODIFIED_DATETIME = "last_modified"
VULN_LAST_CHANGE = "last_change"
VULN_PRODUCTS = "products"
VULN_PRODUCT_NAME = "name"
VULN_PRODUCT_VENDOR = "vendor"
VULN_PRODUCT_VERSION = "version"
VULN_EXPLOITS = "exploits"
VULN_EXPLOIT_SOURCE = "source"
VULN_EXPLOIT_URL = "url"
VULN_REMEDIATIONS = "remediations"
VULN_REMEDIATION_SOURCE = "source"
VULN_REMEDIATION_URL = "url"
VULN_REMEDIATION_DESCRIPTION = "description"
VULN_REFERENCES = "references"
VULN_EXTERNAL_REFERENCES = "external_references"
VULN_PATCHES = "patches"
VULN_PATCH_ID = "id"
VULN_PATCH_PRODUCT = "product"
VULN_PATCH_URL = "url"
VULN_PATCH_DESCRIPTION = "description"

